txt:`file-text-o`
jpg:`file-image-o`
png:`file-image-o`
gif:`file-image-o`
svg:`file-image-o`
mp3:`file-audio-o`
ogg:`file-audio-o`
avi:`file-video-o`
mp4:`file-video-o`
pdf:`file-pdf-o`
v:`file-code-o`
js:`file-code-o`
vmp:`file-code-o`
htm:`file-code-o`
css:`file-code-o`
php:`file-code-o`
zip:`file-archive-o`
html:`file-code-o`
json:`file-code-o`
file:`file-o`
fold:`folder-open`
