3gp:`video/3gpp`
au:`audio/basic`
avi:`video/x-msvideo`
bin:`application/octet-stream`
bmp:`image/bmp`
crt:`application/x-x509-ca-cert`
css:`text/css`
csv:`text/csv`
flac:`audio/x-flac`
fnt:`text/plain`
gif:`image/gif`
gpx:`text/xml`
htm:`text/html`
html:`text/html`
ico:`image/x-icon`
ics:`text/calendar`
iso:`application/x-iso9660-image`
jar:`application/java-archive`
jpeg:`image/jpeg`
jpg:`image/jpeg`
js:`application/javascript`
jso:`application/json`
json:`application/json`
md:`text/x-markdown`
mkv:`video/x-matroska`
mobi:`application/x-mobipocket-ebook`
mp3:`audio/mpeg`
mp4:`video/mp4`
mpeg:`video/mpeg`
oga:`audio/ogg`
ogg:`audio/ogg`
ogv:`video/ogg`
ogx:`application/ogg`
otf:`application/x-font-otf`
pdf:`application/pdf`
png:`image/png`
svg:`image/svg+xml`
svgz:`image/svg+xml`
swf:`application/x-shockwave-flash`
ttf:`application/x-font-ttf`
txt:`text/plain`
uri:`text/uri-list`
v:`text/x-vamp`
vmp:`text/x-vamp`
vcf:`text/x-vcard`
vcs:`text/x-vcalendar`
wav:`audio/x-wav`
weba:`audio/webm`
webm:`video/webm`
webp:`image/webp`
woff:`application/x-font-woff`
xml:`text/xml`
zip:`application/zip`
